# Generated by Django 5.1 on 2025-01-02 06:50

import uuid
from django.db import migrations, models

def backfill_uuid(apps, schema_editor):
    VulnerablePaths = apps.get_model("scanpipe", "VulnerablePaths")
    for obj in VulnerablePaths.objects.filter(uuid__isnull=True):
        obj.uuid = uuid.uuid4()
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', 'previous_migration'),
    ]

    operations = [
        migrations.RunPython(backfill_uuid),
    ]

class Migration(migrations.Migration):
    dependencies = [
        ('scanpipe', '0069_remove_discovereddependency_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerablepaths',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=False),
        ),

        migrations.RunPython(backfill_uuid),
    ]