# Generated by Django 5.1 on 2025-01-02 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0070_vulnerablepaths_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerablepaths',
            name='id',
        ),
        migrations.AlterField(
            model_name='vulnerablepaths',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]