# Generated by Django 5.1 on 2025-02-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0071_remove_vulnerablepaths_id_alter_vulnerablepaths_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionablePackageAvailableVersions',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('scan_status', models.CharField(max_length=20)),
                ('package_url', models.CharField(max_length=300)),
                ('version', models.CharField(max_length=100)),
                ('is_latest', models.BooleanField()),
                ('vulns_count', models.IntegerField(blank=True, null=True)),
                ('scan_output', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('scancode_project_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('is_version_in_use', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actionable_package_available_versions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CronJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('command', models.CharField(max_length=512)),
                ('timeout', models.IntegerField(blank=True, null=True)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('is_weekly', models.BooleanField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_run_output', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cron_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepositoryActionablePackageAvailableVersionsAssociation',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('environment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'repository_actionable_package_available_versions_association',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepositoryActionablePackageVersions',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('environment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'repository_actionable_package_versions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SafeActionable',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('package_url', models.CharField(max_length=300, unique=True)),
                ('current_max_version', models.CharField(blank=True, max_length=100, null=True)),
                ('next_safe_version', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('scan_complete', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'safe_actionable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanpipeCodebaserelation',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('extra_data', models.JSONField()),
                ('map_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'scanpipe_codebaserelation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanpipeCodebaseresource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2000)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('sha1', models.CharField(max_length=40)),
                ('md5', models.CharField(max_length=32)),
                ('sha256', models.CharField(max_length=64)),
                ('sha512', models.CharField(max_length=128)),
                ('copyrights', models.JSONField()),
                ('holders', models.JSONField()),
                ('authors', models.JSONField()),
                ('emails', models.JSONField()),
                ('urls', models.JSONField()),
                ('rootfs_path', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('extra_data', models.JSONField()),
                ('name', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=100)),
                ('programming_language', models.CharField(max_length=50)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=1024)),
                ('compliance_alert', models.CharField(max_length=10)),
                ('is_archive', models.BooleanField()),
                ('is_binary', models.BooleanField()),
                ('is_text', models.BooleanField()),
                ('is_key_file', models.BooleanField()),
                ('is_media', models.BooleanField()),
                ('tag', models.CharField(max_length=50)),
                ('package_data', models.JSONField()),
                ('detected_license_expression', models.TextField()),
                ('detected_license_expression_spdx', models.TextField()),
                ('license_detections', models.JSONField()),
                ('license_clues', models.JSONField()),
                ('percentage_of_license_text', models.FloatField(blank=True, null=True)),
                ('is_legal', models.BooleanField()),
                ('is_manifest', models.BooleanField()),
                ('is_readme', models.BooleanField()),
                ('is_top_level', models.BooleanField()),
            ],
            options={
                'db_table': 'scanpipe_codebaseresource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanpipeDiscovereddependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_uid', models.CharField(max_length=1024)),
                ('extracted_requirement', models.CharField(max_length=256)),
                ('scope', models.CharField(max_length=64)),
                ('datasource_id', models.CharField(max_length=64)),
                ('is_runtime', models.BooleanField()),
                ('is_optional', models.BooleanField()),
                ('is_resolved', models.BooleanField()),
                ('affected_by_vulnerabilities', models.JSONField()),
                ('is_direct', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('namespace', models.CharField(max_length=255)),
                ('qualifiers', models.CharField(max_length=1024)),
                ('subpath', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=16)),
                ('version', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scanpipe_discovereddependency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanpipeDiscoveredpackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('namespace', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('qualifiers', models.CharField(max_length=1024)),
                ('subpath', models.CharField(max_length=200)),
                ('uuid', models.UUIDField(unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('primary_language', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('homepage_url', models.CharField(max_length=1024)),
                ('download_url', models.CharField(max_length=2048)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('sha1', models.CharField(max_length=40)),
                ('md5', models.CharField(max_length=32)),
                ('bug_tracking_url', models.CharField(max_length=1024)),
                ('code_view_url', models.CharField(max_length=1024)),
                ('vcs_url', models.CharField(max_length=1024)),
                ('copyright', models.TextField()),
                ('declared_license_expression', models.TextField()),
                ('extracted_license_statement', models.TextField()),
                ('notice_text', models.TextField()),
                ('missing_resources', models.JSONField()),
                ('modified_resources', models.JSONField()),
                ('keywords', models.JSONField()),
                ('source_packages', models.JSONField()),
                ('extra_data', models.JSONField()),
                ('package_uid', models.CharField(max_length=1024)),
                ('api_data_url', models.CharField(max_length=1024)),
                ('file_references', models.JSONField()),
                ('parties', models.JSONField()),
                ('repository_download_url', models.CharField(max_length=1024)),
                ('repository_homepage_url', models.CharField(max_length=1024)),
                ('sha256', models.CharField(max_length=64)),
                ('sha512', models.CharField(max_length=128)),
                ('declared_license_expression_spdx', models.TextField()),
                ('holder', models.TextField()),
                ('license_detections', models.JSONField()),
                ('other_license_detections', models.JSONField()),
                ('other_license_expression', models.TextField()),
                ('other_license_expression_spdx', models.TextField()),
                ('affected_by_vulnerabilities', models.JSONField()),
                ('compliance_alert', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=50)),
                ('datasource_ids', models.JSONField()),
                ('datafile_paths', models.JSONField()),
                ('is_private', models.BooleanField()),
                ('is_virtual', models.BooleanField()),
                ('notes', models.TextField()),
            ],
            options={
                'db_table': 'scanpipe_discoveredpackage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanpipeDiscoveredpackageCodebaseResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'scanpipe_discoveredpackage_codebase_resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanpipeInputsource',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('download_url', models.CharField(max_length=4000)),
                ('filename', models.CharField(max_length=255)),
                ('is_uploaded', models.BooleanField()),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'scanpipe_inputsource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanpipeProject',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('work_directory', models.CharField(max_length=2048)),
                ('extra_data', models.JSONField()),
                ('is_archived', models.BooleanField()),
                ('notes', models.TextField()),
                ('settings', models.JSONField()),
                ('slug', models.CharField(max_length=110, unique=True)),
                ('wasp_uuid_id', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'db_table': 'scanpipe_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanpipeProjectmessage',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('severity', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('model', models.CharField(max_length=100)),
                ('details', models.JSONField()),
                ('traceback', models.TextField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'scanpipe_projectmessage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanpipeRun',
            fields=[
                ('task_id', models.UUIDField(blank=True, null=True)),
                ('task_start_date', models.DateTimeField(blank=True, null=True)),
                ('task_end_date', models.DateTimeField(blank=True, null=True)),
                ('task_exitcode', models.IntegerField(blank=True, null=True)),
                ('task_output', models.TextField()),
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('pipeline_name', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('log', models.TextField()),
                ('scancodeio_version', models.CharField(max_length=100)),
                ('current_step', models.CharField(max_length=256)),
                ('selected_groups', models.JSONField(blank=True, null=True)),
                ('selected_steps', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scanpipe_run',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanpipeUuidtaggeditem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
            ],
            options={
                'db_table': 'scanpipe_uuidtaggeditem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanpipeWebhookdelivery',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('target_url', models.CharField(max_length=1024)),
                ('sent_date', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_text', models.TextField()),
                ('delivery_error', models.TextField()),
            ],
            options={
                'db_table': 'scanpipe_webhookdelivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanpipeWebhooksubscription',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('target_url', models.CharField(max_length=1024)),
                ('created_date', models.DateTimeField()),
                ('include_results', models.BooleanField()),
                ('include_summary', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('trigger_on_each_run', models.BooleanField()),
            ],
            options={
                'db_table': 'scanpipe_webhooksubscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaggitTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'taggit_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaggitTaggeditem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
            ],
            options={
                'db_table': 'taggit_taggeditem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempProjectIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temp_project_ids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempProjectName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'temp_project_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TmpActionableWasp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasp_uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tmp_actionable_wasp',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Secbugs',
        ),
    ]
