# Generated by Django 5.1.11 on 2025-11-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0072_actionablepackageavailableversions_authgroup_and_more'),
        ('scanpipe', '0076_discoveredpackagescore_scorecardcheck_and_more'),
    ]

    operations = [
    ]
